#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MisWebsite")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttMember(tMember instance);
  partial void UpdatetMember(tMember instance);
  partial void DeletetMember(tMember instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MisWebsiteConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tMember> tMembers
	{
		get
		{
			return this.GetTable<tMember>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tMembers")]
public partial class tMember : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _member_id;
	
	private System.Nullable<bool> _is_active;
	
	private string _DESKCASE_APP_USER_HD;
	
	private System.Nullable<bool> _DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE;
	
	private System.Nullable<bool> _DESKCASE_APP_ALLOWED;
	
	private System.Nullable<bool> _ECASE_APP_ALLOW;
	
	private System.Nullable<int> _ECASE_APP_LEVEL;
	
	private string _admin_level_param;
	
	private System.Nullable<int> _admin_level;
	
	private string _first_name;
	
	private string _last_name;
	
	private string _email;
	
	private string _password;
	
	private string _address;
	
	private string _country;
	
	private string _city;
	
	private string _state;
	
	private string _zip_code;
	
	private string _phone_home;
	
	private string _phone_office;
	
	private string _phone_mobile;
	
	private System.Nullable<bool> _receive_notifications;
	
	private System.Nullable<System.DateTime> _date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmember_idChanging(int value);
    partial void Onmember_idChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    partial void OnDESKCASE_APP_USER_HDChanging(string value);
    partial void OnDESKCASE_APP_USER_HDChanged();
    partial void OnDESKCASE_APP_USER_ALLOW_CLOUD_MANAGEChanging(System.Nullable<bool> value);
    partial void OnDESKCASE_APP_USER_ALLOW_CLOUD_MANAGEChanged();
    partial void OnDESKCASE_APP_ALLOWEDChanging(System.Nullable<bool> value);
    partial void OnDESKCASE_APP_ALLOWEDChanged();
    partial void OnECASE_APP_ALLOWChanging(System.Nullable<bool> value);
    partial void OnECASE_APP_ALLOWChanged();
    partial void OnECASE_APP_LEVELChanging(System.Nullable<int> value);
    partial void OnECASE_APP_LEVELChanged();
    partial void Onadmin_level_paramChanging(string value);
    partial void Onadmin_level_paramChanged();
    partial void Onadmin_levelChanging(System.Nullable<int> value);
    partial void Onadmin_levelChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void Onzip_codeChanging(string value);
    partial void Onzip_codeChanged();
    partial void Onphone_homeChanging(string value);
    partial void Onphone_homeChanged();
    partial void Onphone_officeChanging(string value);
    partial void Onphone_officeChanged();
    partial void Onphone_mobileChanging(string value);
    partial void Onphone_mobileChanged();
    partial void Onreceive_notificationsChanging(System.Nullable<bool> value);
    partial void Onreceive_notificationsChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
	
	public tMember()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_member_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int member_id
	{
		get
		{
			return this._member_id;
		}
		set
		{
			if ((this._member_id != value))
			{
				this.Onmember_idChanging(value);
				this.SendPropertyChanging();
				this._member_id = value;
				this.SendPropertyChanged("member_id");
				this.Onmember_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
	public System.Nullable<bool> is_active
	{
		get
		{
			return this._is_active;
		}
		set
		{
			if ((this._is_active != value))
			{
				this.Onis_activeChanging(value);
				this.SendPropertyChanging();
				this._is_active = value;
				this.SendPropertyChanged("is_active");
				this.Onis_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESKCASE_APP_USER_HD", DbType="NVarChar(255)")]
	public string DESKCASE_APP_USER_HD
	{
		get
		{
			return this._DESKCASE_APP_USER_HD;
		}
		set
		{
			if ((this._DESKCASE_APP_USER_HD != value))
			{
				this.OnDESKCASE_APP_USER_HDChanging(value);
				this.SendPropertyChanging();
				this._DESKCASE_APP_USER_HD = value;
				this.SendPropertyChanged("DESKCASE_APP_USER_HD");
				this.OnDESKCASE_APP_USER_HDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE", DbType="Bit")]
	public System.Nullable<bool> DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE
	{
		get
		{
			return this._DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE;
		}
		set
		{
			if ((this._DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE != value))
			{
				this.OnDESKCASE_APP_USER_ALLOW_CLOUD_MANAGEChanging(value);
				this.SendPropertyChanging();
				this._DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE = value;
				this.SendPropertyChanged("DESKCASE_APP_USER_ALLOW_CLOUD_MANAGE");
				this.OnDESKCASE_APP_USER_ALLOW_CLOUD_MANAGEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESKCASE_APP_ALLOWED", DbType="Bit")]
	public System.Nullable<bool> DESKCASE_APP_ALLOWED
	{
		get
		{
			return this._DESKCASE_APP_ALLOWED;
		}
		set
		{
			if ((this._DESKCASE_APP_ALLOWED != value))
			{
				this.OnDESKCASE_APP_ALLOWEDChanging(value);
				this.SendPropertyChanging();
				this._DESKCASE_APP_ALLOWED = value;
				this.SendPropertyChanged("DESKCASE_APP_ALLOWED");
				this.OnDESKCASE_APP_ALLOWEDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECASE_APP_ALLOW", DbType="Bit")]
	public System.Nullable<bool> ECASE_APP_ALLOW
	{
		get
		{
			return this._ECASE_APP_ALLOW;
		}
		set
		{
			if ((this._ECASE_APP_ALLOW != value))
			{
				this.OnECASE_APP_ALLOWChanging(value);
				this.SendPropertyChanging();
				this._ECASE_APP_ALLOW = value;
				this.SendPropertyChanged("ECASE_APP_ALLOW");
				this.OnECASE_APP_ALLOWChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECASE_APP_LEVEL", DbType="Int")]
	public System.Nullable<int> ECASE_APP_LEVEL
	{
		get
		{
			return this._ECASE_APP_LEVEL;
		}
		set
		{
			if ((this._ECASE_APP_LEVEL != value))
			{
				this.OnECASE_APP_LEVELChanging(value);
				this.SendPropertyChanging();
				this._ECASE_APP_LEVEL = value;
				this.SendPropertyChanged("ECASE_APP_LEVEL");
				this.OnECASE_APP_LEVELChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_level_param", DbType="NVarChar(50)")]
	public string admin_level_param
	{
		get
		{
			return this._admin_level_param;
		}
		set
		{
			if ((this._admin_level_param != value))
			{
				this.Onadmin_level_paramChanging(value);
				this.SendPropertyChanging();
				this._admin_level_param = value;
				this.SendPropertyChanged("admin_level_param");
				this.Onadmin_level_paramChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_level", DbType="Int")]
	public System.Nullable<int> admin_level
	{
		get
		{
			return this._admin_level;
		}
		set
		{
			if ((this._admin_level != value))
			{
				this.Onadmin_levelChanging(value);
				this.SendPropertyChanging();
				this._admin_level = value;
				this.SendPropertyChanged("admin_level");
				this.Onadmin_levelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50)")]
	public string first_name
	{
		get
		{
			return this._first_name;
		}
		set
		{
			if ((this._first_name != value))
			{
				this.Onfirst_nameChanging(value);
				this.SendPropertyChanging();
				this._first_name = value;
				this.SendPropertyChanged("first_name");
				this.Onfirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
	public string last_name
	{
		get
		{
			return this._last_name;
		}
		set
		{
			if ((this._last_name != value))
			{
				this.Onlast_nameChanging(value);
				this.SendPropertyChanging();
				this._last_name = value;
				this.SendPropertyChanged("last_name");
				this.Onlast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(255)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(50)")]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip_code", DbType="NVarChar(50)")]
	public string zip_code
	{
		get
		{
			return this._zip_code;
		}
		set
		{
			if ((this._zip_code != value))
			{
				this.Onzip_codeChanging(value);
				this.SendPropertyChanging();
				this._zip_code = value;
				this.SendPropertyChanged("zip_code");
				this.Onzip_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_home", DbType="NVarChar(50)")]
	public string phone_home
	{
		get
		{
			return this._phone_home;
		}
		set
		{
			if ((this._phone_home != value))
			{
				this.Onphone_homeChanging(value);
				this.SendPropertyChanging();
				this._phone_home = value;
				this.SendPropertyChanged("phone_home");
				this.Onphone_homeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_office", DbType="NVarChar(50)")]
	public string phone_office
	{
		get
		{
			return this._phone_office;
		}
		set
		{
			if ((this._phone_office != value))
			{
				this.Onphone_officeChanging(value);
				this.SendPropertyChanging();
				this._phone_office = value;
				this.SendPropertyChanged("phone_office");
				this.Onphone_officeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_mobile", DbType="NVarChar(50)")]
	public string phone_mobile
	{
		get
		{
			return this._phone_mobile;
		}
		set
		{
			if ((this._phone_mobile != value))
			{
				this.Onphone_mobileChanging(value);
				this.SendPropertyChanging();
				this._phone_mobile = value;
				this.SendPropertyChanged("phone_mobile");
				this.Onphone_mobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receive_notifications", DbType="Bit")]
	public System.Nullable<bool> receive_notifications
	{
		get
		{
			return this._receive_notifications;
		}
		set
		{
			if ((this._receive_notifications != value))
			{
				this.Onreceive_notificationsChanging(value);
				this.SendPropertyChanging();
				this._receive_notifications = value;
				this.SendPropertyChanged("receive_notifications");
				this.Onreceive_notificationsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
